import turtle
tina = turtle.Turtle()
tina.color("black")
tina.pensize(6)


tina.fillcolor("darkred")
tina.begin_fill()
tina.left(135)
tina.forward(75)
tina.right(45)
tina.forward(75)
tina.right(45)
tina.forward(75)
tina.right(45)
tina.forward(75)
tina.right(45)
tina.forward(75)
tina.right(45)
tina.forward(75)
tina.right(45)
tina.forward(75)
tina.right(45)
tina.forward(75)
tina.end_fill()
